version: "3.9"

services:
  db:
    image: postgres:15
    env_file:
      - bolmate-base-core/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./bolmate-base-core
    env_file:
      - bolmate-base-core/.env
    ports:
      - "5000:5000"
    volumes:
      - ./bolmate-base-core:/app
      - /app/__pycache__
      - /app/.pytest_cache
    depends_on:
      - db

  frontend:
    build: ./bolmate-base-front
    env_file:
      - bolmate-base-front/.env
    ports:
      - "3000:3000"
    volumes:
      - ./bolmate-base-front:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  db_data:
