version: '3.9'
#TODO aplikacja w trybie deweloperskim docker-compose.dev
#  - współdzielone pliki między hostem a kontenerem
#TODO aplikacja trybie produkcyjnym osobny docker-compose.prod
#  - nie współdzielone pliki między hostem a kontenerem
#  - własna sieć

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bolmate_base
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./bolmate-base-core
    env_file:
      - ./bolmate-base-core/.env
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build: ./bolmate-base-front
    env_file:
      - ./bolmate-base-front/.env
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  postgres_data:
